language: php

services:
    - redis-server
    - elasticsearch
    - rabbitmq

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm

matrix:
    allow_failures:
        - php: hhvm
        - php: 7.0

before_script:
    - composer self-update
    - composer install --dev

script:
    - mkdir -p build/logs
    - make sniff test

after_script:
    - CODECLIMATE_REPO_TOKEN=aaf8c4cfec2a0e80d50992af6d41e35cfeefca12edf92caccba7771d6cfed423 ./vendor/bin/test-reporter